name: example
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.2.6
  at_utils: ^3.0.11
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2
  at_app_flutter: ^5.0.1
  at_onboarding_flutter: ^5.0.3
  biometric_storage: ^4.1.3
  at_collection_generator:
    path: ../
  at_client:
    path: /Users/niteshkumar/Desktop/client_projects/at_client_sdk/packages/at_client
  
dependency_overrides:
  test: ^1.22.1
  test_api: 0.4.12
  at_client:
    path: /Users/niteshkumar/Desktop/client_projects/at_client_sdk/packages/at_client


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: "2.3.3"

flutter:
  uses-material-design: true
  assets:
    - .env

