import 'dart:async';

import 'package:at_auth/src/enroll/at_enrollment_impl.dart';
import 'package:at_auth/src/enroll/models/at_enrollment_request.dart';
import 'package:at_auth/src/enroll/models/at_enrollment_response.dart';
import 'package:at_auth/src/enroll/models/enrollment_request_decision.dart';
import 'package:at_auth/src/enroll/models/otp.dart';
import 'package:at_commons/at_commons.dart';
import 'package:at_lookup/at_lookup.dart';
import 'package:at_utils/at_progress.dart';

/// An abstract class for submitting and managing the enrollment requests.
abstract class AtEnrollment {
  factory AtEnrollment.create() {
    return AtEnrollmentImpl();
  }

  /// How long [waitForApproval] leaves between polls when a caller states no
  /// interval of its own.
  static const Duration defaultRetryInterval = Duration(seconds: 2);

  /// How many consecutive failures to reach the atServer [waitForApproval]
  /// rides out when a caller states no budget of its own. It has never
  /// bounded the wait for a decision — see [waitForApproval].
  static const int defaultMaxRetries = 15;

  /// Whether [waitForApproval] narrates itself on [progressStream] when a
  /// caller states no preference.
  static const bool defaultLogProgress = true;

  /// How long a passcode from [generateOtp] or [setSpp] stays valid when a
  /// caller states no expiry of its own.
  static const Duration defaultOtpExpiry = Duration(minutes: 5);

  Stream<ProgressEvent> get progressStream;

  /// Submits an enrollment request.
  ///
  /// The [BaseEnrollmentRequest] is an abstract class and serves as the entity responsible for submitting the enrollment request. This
  /// class contains fields that are shared between the [FirstEnrollmentRequest] and [EnrollmentRequest] which are subclasses of
  /// [BaseEnrollmentRequest].
  ///
  /// Use the [FirstEnrollmentRequest] when onboarding (activating) an @ sign for the initial time. Upon submitting the
  /// [FirstEnrollmentRequest], an APKAM key pair and an encryption key pair are generated, and an enrollment request is sent to the
  /// server. The server assigns the "__manage" namespace, which has access to all namespaces and serves as the administrator app
  /// responsible for approving subsequent enrollment requests.
  ///
  /// The enrollment request is auto-approved. When an @ sign is initially onboarded and the enableEnrollment flag is set to
  /// true in AtClientPreferences, the enrollment is sent to the server. In this scenario, because there's no app available for
  /// approval yet, the initial enrollment (submitted over a CRAM authenticated connection) is automatically approved.
  /// Conversely, if enableEnrollment is set to false, the enrollment isn't submitted, which means subsequent enrollment requests
  /// cannot be approved by the app.
  ///
  /// ```dart
  /// Example on submitting FirstEnrollmentRequest
  ///   FirstEnrollmentRequest firstEnrollmentRequest = FirstEnrollmentRequest(
  ///               appName: 'wavi',
  ///               deviceName: 'iphone',
  ///               apkamPublicKey: 'dummy-apkam-public key', // Generated by the system
  ///               encryptedDefaultEncryptionPrivateKey: 'dummy-encrypted-private-key', // Generated by the system and encrypted by the APKAM symmetric key
  ///               encryptedDefaultSelfEncryptionKey: 'dummy-self-encryption-key'); // Generated by the system and encrypted by the APKAM symmetric key);
  ///
  ///     AtEnrollmentResponse? atEnrollmentResponse =
  ///         await atEnrollmentBase?.submit(initialEnrollmentRequest, atLookUp!);
  ///```
  /// Use [AtEnrollmentRequest] to submit subsequent enrollment requests to generate APKAM key-pair with limited access to the
  /// specified namespaces. The [AtEnrollmentRequest] accepts a [AtAuthSession] (the source of the atSign, rootDomain and the
  /// atKeysIo the new keys are persisted into) plus the enrollment-specific appName, deviceName, namespaces and otp.
  ///
  /// ```dart
  /// Example on submitting AtEnrollmentRequest
  ///   AtEnrollmentRequest enrollmentRequest = AtEnrollmentRequest(
  ///                     session: session, // atSign + rootDomain + atKeysIo destination
  ///                     appName: 'wavi',
  ///                     deviceName: 'my-device',
  ///                     namespaces: {'wavi': 'rw'},
  ///                     otp: '123');
  ///
  ///     AtEnrollmentResponse atEnrollmentResponse =
  ///         await atEnrollmentBase.submit(enrollmentRequest, atLookUp);
  ///     await atEnrollmentBase.waitForApproval(atEnrollmentResponse);
  ///     // atEnrollmentResponse.session -> AtClientManager.fromAuthSession(...)
  ///```
  ///
  /// The [atLookUp] parameter is used to perform lookups to secondary server to submit an enrollment request.
  ///
  /// Returns a [Future] containing an [AtEnrollmentResponse] representing the
  /// result of the enrollment.
  ///
  Future<AtEnrollmentResponse> submit(
      EnrollmentRequest enrollmentRequest, AtLookUp atLookUp);

  /// Approves an enrollment request.
  ///
  /// Accepts [EnrollmentRequestDecision] which encapsulates the necessary enrollment request details for approving the
  /// enrollment request.
  ///
  /// To approve the request, the "enrollmentId" and its corresponding "encryptedAPKAMSymmetricKey,"
  /// received through the notification, must be provided using the "AuthenticationRequestDecisionBuilder."
  ///
  /// Upon approval, the encryptedAPKAMSymmetricKey undergoes decryption using the default encryption public key to
  /// retrieve the original APKAM Symmetric key. Subsequently, the default encryption key pair and the self-encryption
  /// key are encrypted with the APKAM symmetric key and transmitted to the server.
  ///
  /// The [atLookUp] parameter is used to perform lookups during approval management.
  ///
  /// Returns a [Future] containing an [AtEnrollmentResponse] representing the result of the approval/denial of an enrollment.
  ///
  /// ```dart
  ///  To approve an enrollment request
  ///
  /// AtEnrollmentBase atEnrollmentBase = AtEnrollmentImpl('@alice');
  /// AtLookup atLookup = AtLookupImpl('@alice', 'dummy-root-domain', 64);
  ///
  /// EnrollmentRequestDecision enrollmentRequestDecision =
  ///           EnrollmentRequestDecision.approved(ApprovedRequestDecisionBuilder(
  ///               enrollmentId: 'dummy-enrollment-id',
  ///               encryptedAPKAMSymmetricKey: 'dummy-encrypted-apkam-symmetric-key'));
  ///
  /// AtEnrollmentResponse atEnrollmentResponse = await atEnrollmentBase.approve(
  ///       enrollmentRequestDecision, atLookupImpl);
  /// ```
  Future<AtEnrollmentResponse> approve(
      EnrollmentRequestDecision enrollmentRequestDecision, AtLookUp atLookUp);

  /// Denies an enrollment request.
  ///
  /// Accepts [EnrollmentRequestDecision] which encapsulates the enrollment request details necessary to deny an enrollment.
  /// The [atLookUp] parameter is used to perform lookups during approval management.
  ///
  /// Returns a [Future] containing an [AtEnrollmentResponse] representing the result of the approval/denial of an enrollment.
  ///
  /// ```dart
  ///  To deny an enrollment request
  ///
  /// AtEnrollmentBase atEnrollmentBase = AtEnrollmentImpl('@alice');
  /// AtLookup atLookup = AtLookupImpl('@alice', 'dummy-root-domain', 64);
  ///
  /// EnrollmentRequestDecision enrollmentRequestDecision = EnrollmentRequestDecision.denied('dummy-enrollment-id');
  /// AtEnrollmentResponse atEnrollmentResponse = await atEnrollmentBase.deny(enrollmentRequestDecision, atLookupImpl);
  /// ```
  Future<AtEnrollmentResponse> deny(
      EnrollmentRequestDecision enrollmentRequestDecision, AtLookUp atLookUp);

  /// Revokes an approved enrollment, closing any active connections and making it inactive for future use.
  ///
  /// Accepts [EnrollmentRequestDecision] which encapsulates the enrollment request details necessary to revoke an enrollment.
  /// The [atLookUp] parameter is used to perform lookups during approval management.
  ///
  /// Returns a [Future] containing an [AtEnrollmentResponse] representing the result of the revoke of an enrollment.
  ///
  /// ```dart
  ///  To revoke an enrollment request
  ///
  /// AtEnrollmentBase atEnrollmentBase = AtEnrollmentImpl('@alice');
  /// AtLookup atLookup = AtLookupImpl('@alice', 'dummy-root-domain', 64);
  ///
  /// EnrollmentRequestDecision enrollmentRequestDecision = EnrollmentRequestDecision.revoked('dummy-enrollment-id');
  /// AtEnrollmentResponse atEnrollmentResponse = await atEnrollmentBase.revoke(enrollmentRequestDecision, atLookupImpl);
  /// ```
  Future<AtEnrollmentResponse> revoke(
      EnrollmentRequestDecision enrollmentRequestDecision, AtLookUp atLookUp);

  /// Lists all enrollments.
  ///
  /// Accepts [EnrollmentStatus] inside the [statusFilters] parameter to filter enrollments with their current status.
  ///
  /// Returns a [Future] containing a [List<EnrollmentServerRequest>] representing all the enrollments.
  Future<List<EnrollmentServerResponse>> list(
      List<EnrollmentStatus>? statusFilters, AtLookUp atLookUp,
      {String? arx, String? drx});

  /// Generates a one-time passcode from the server.
  ///
  /// [expiry] defaults to [defaultOtpExpiry].
  Future<Otp> generateOtp(AtLookUp atLookUp,
      {Duration expiry = defaultOtpExpiry});

  /// Sets a semi-permanent passcode on the server.
  ///
  /// [spp] must be alphanumeric and exactly 6 characters.
  /// [expiry] defaults to [defaultOtpExpiry].
  Future<Otp> setSpp(String spp, AtLookUp atLookUp,
      {Duration expiry = defaultOtpExpiry});

  /// Polls for the approval or denial of an enrollment request, and on
  /// approval collects and decrypts what the approval released.
  ///
  /// **The wait for a decision is unbounded.** Somebody has to decide this
  /// request, on their own schedule, so polling continues until the atServer
  /// reports approval or denial — for as long as that takes. No parameter
  /// here shortens it; a caller that needs to give up must race this against
  /// its own timer.
  ///
  /// [maxRetries] is a budget for **consecutive failures to reach the
  /// atServer**, and nothing else — the exit from an atServer that is
  /// genuinely gone. An answer restores it, including a refusal, which is an
  /// answer about the enrollment. Exhausting it propagates the underlying
  /// connection failure.
  ///
  /// [retryInterval] is the pause between polls, and [logProgress] narrates
  /// the wait on [progressStream] (which costs a brief additional pause per
  /// attempt). Their defaults, and [maxRetries]', are
  /// [defaultRetryInterval], [defaultLogProgress] and [defaultMaxRetries].
  ///
  /// Dart resolves a default in the method that runs, not from the type of
  /// the reference a caller holds, so what an implementation declares here
  /// is what its callers actually get and what is declared on this interface
  /// is documentation. Naming the same constants on both is what keeps that
  /// documentation true.
  ///
  /// ```dart
  /// AtEnrollment atEnrollment = AtEnrollment.create();
  ///
  /// AtEnrollmentResponse? atEnrollmentResponse =
  ///         await atEnrollmentBase?.submit(dummyEnrollmentRequest, atLookUp!);
  ///
  /// try{
  ///   await atEnrollment.waitForApproval(
  ///     enrollmentResponse: atEnrollmentResponse!,
  ///   );
  /// }catch{
  ///   // Handle errors
  /// }
  /// ```
  /// [atLookup] is the connection the approval handshake runs on — the PKAM
  /// retries and the post-approval key fetches. When null, one is built from
  /// the response's atSign and rootDomain.
  Future<void> waitForApproval(
    AtEnrollmentResponse enrollmentResponse, {
    bool logProgress = defaultLogProgress,
    int maxRetries = defaultMaxRetries,
    Duration retryInterval = defaultRetryInterval,
    AtLookUp? atLookup,
  });
}
