name: at_stream
description: Stream data over the atPlatform
version: 0.1.0-dev.1
repository: https://github.com/atsign-foundation/at_client_sdk/tree/trunk/packages/at_stream
homepage: https://atsign.com
documentation: https://docs.atsign.com/

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  at_client: ^3.7.0
  at_utils: ^3.0.19
  at_commons: ^5.5.0
  meta: ^1.16.0
  stream_channel: ^2.1.4
  async: ^2.13.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.0
  # example dependencies:
  dart_mcp: ^0.3.3
  args: ^2.6.0
  at_cli_commons: ^3.0.0
