name: Setup Flutter and Dart
description: |
  Installs flutter & dart, using a non-flutter dart binary of specified channel

inputs:
  flutter-channel:
    required: false
    description: Flutter channel to install
    default: "stable"
  dart-channel:
    required: false
    description: Dart channel to install
    default: stable

runs:
  using: composite
  steps:
    - name: Get latest Flutter stable commit
      shell: bash
      id: flutter-ref
      run: |
        sha=$(
        cat flutter_ref-${{ inputs.flutter-channel }}
        )
        echo "sha=$sha" >> "$GITHUB_OUTPUT"
      working-directory: ./actions/setup-flutter-and-dart/

    - name: Install Flutter
      uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225 #v2.12.0
      with:
        channel: ${{ inputs.flutter-channel }}
        cache: ${{ steps.flutter-ref.outputs.sha }}
        cache-key: ${{ steps.flutter-ref.outputs.sha }}

    - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
      with:
        sdk: ${{ inputs.dart-channel}}

    - name: Ensure dart on path is not from Flutter SDK
      shell: bash
      run: |
        if which dart | grep -q "flutter"; then
          exit 1
        fi
