# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://pub.dev/packages/lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    camel_case_types : true
    unnecessary_string_interpolations : true
    await_only_futures : true
    unawaited_futures: true
    depend_on_referenced_packages : false
    # temporary flag till private key reference is fully removed
    deprecated_member_use: false

#analyzer:
#   exclude:
#     - path/to/excluded/files/**

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
    - no-equal-then-else
#    - newline-before-return
#    - prefer-trailing-comma