name: at_client
description: The at_client library is the non-platform specific Client SDK which provides the essential methods for building an app using the atProtocol.

##
##
## NB: When incrementing the version, please also increment the version in AtClientConfig file
version: 3.3.0
## NB: When incrementing the version, please also increment the version in AtClientConfig file
##

repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://docs.atsign.com/

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  path: ^1.8.2
  hive: ^2.2.3
  asn1lib: ^1.5.3
  crypton: ^2.2.1
  encrypt: ^5.0.3
  cron: ^0.5.1
  convert: ^3.0.2
  uuid: ^3.0.7
  crypto: ^3.0.3
  collection: ^1.16.0
  archive: ^3.6.1
  http: ">=0.13.5 <2.0.0"
  internet_connection_checker: ^1.0.0+1
  async: ^2.9.0
  at_utf7: ^1.0.0
  at_base2e15: ^1.0.0
  at_commons: ^5.0.0
  at_utils: ^3.0.19
  at_chops: ^2.0.1
  at_lookup: ^3.0.49
  at_auth: ^2.0.7
  at_persistence_spec: ^2.0.14
  at_persistence_secondary_server: ^3.0.64
  meta: ^1.8.0
  version: ^3.0.2

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_commons
      ref: sync_skip_delete

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.4
  at_demo_data: ^1.0.1
  coverage: ^1.5.0
  mocktail: ^1.0.3
