name: at_client
description: The at_client library is the non-platform specific Client SDK which provides the essential methods for building an app using the atProtocol.

##
##
## NB: When incrementing the version, please also increment the version in AtClientConfig file
version: 3.0.49
## NB: When incrementing the version, please also increment the version in AtClientConfig file
##

repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://docs.atsign.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: gkc-debugging-branch

dependencies:
  path: ^1.8.2
  hive: ^2.0.4
  crypton: ^2.0.5
  encrypt: ^5.0.1
  cron: ^0.5.0
  convert: ^3.0.2
  uuid: ^3.0.6
  crypto: ^3.0.1
  collection: ^1.16.0
  archive: ^3.3.1
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  async: ^2.9.0
  at_persistence_spec: ^2.0.9
  at_persistence_secondary_server: ^3.0.43
  at_lookup: ^3.0.32
  at_utf7: ^1.0.0
  at_base2e15: ^1.0.0
  at_commons: ^3.0.32
  at_utils: ^3.0.11
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  at_demo_data: ^1.0.0
  coverage: ^1.5.0
  mocktail: ^0.3.0
  dart_code_metrics: ^4.17.0