name: at_client_sdk

packages:
  - packages/*
  - tests/*
ignore:
  - "packages/*/*example*"

command:
  bootstrap:
    runPubGetInParallel: false
    #dependencies:
    #  uuid: ^4.5.1
    #  TODO: See if adding flutter_test resolves meta to the pinned version
    #  meta: ^1.16.0
