name: at_client_sdk

packages:
  - packages/*
  - tests/*
ignore:
  - "packages/*/*example*"

command:
  bootstrap:
    runPubGetInParallel: true
    dependencies:
      # Our dependencies (minimums required for forward compatibility)
      # - When we do major version upgrades to dependencies and our code require
      #   changes this doesn't result in a breaking change in our package
      #   version, but it does result in a minimum version required for
      #   compatibility. Specify that minimum constraint here.
      at_commons: ^5.5.0
      at_client: ^3.7.0

      # Our dependencies in at_server
      at_persistence_secondary_server:
        # Add two ../../ for relative to the packages, not relative to this file
        path: ../../../at_server/packages/at_persistence_secondary_server

      # External dependencies
      # - Setting a version here will set it for the entire workspace
      uuid: ^4.0.0
      meta: ^1.16.0
  version:
    includeScopes: false
    updateGitTagRefs: false
    changelogCommitBodies:
      include: false
