targets:
  $default:
    builders:
      at_collection_generator|at_collection_annotation:
        enabled: true

builders:
  at_collection_generator:
    target: ":at_collection_generator"
    import: "package:at_collection_generator/builder.dart"
    builder_factories: ["atCollectionGenerator"]
    build_extensions: {".dart": [".at_collection.dart"]}
    auto_apply: dependents
    build_to: source