# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - camel_case_types
    - unnecessary_string_interpolations
    - await_only_futures
    - unnecessary_await_in_return
    - unawaited_futures

analyzer:
#   exclude:
#     - path/to/excluded/files/**
