import 'dart:convert';
import 'dart:ffi';
import 'dart:typed_data';

import 'package:at_chops/at_chops_ffi.dart';
import 'package:test/test.dart';

void main() {
  final DynamicLibrary? lib = tryLoadLibCrypto();
  final bool xWingFfi = lib != null && libCryptoSupportsMlKem768(lib);
  final bool mlDsaFfi = lib != null && libCryptoSupportsMlDsa65(lib);
  final bool aesGcmFfi = lib != null && libCryptoSupportsAesGcm(lib);

  group('AtPqc — host-agnostic', () {
    test('AtPqc.xWing is FFI when supported, else pure', () {
      if (xWingFfi) {
        expect(AtPqc.xWing, isA<XWingFfiAlgo>());
      } else {
        expect(AtPqc.xWing, isA<XWingPureDartAlgo>());
      }
    });

    test('AtPqc.mlDsa65 is FFI when supported, else pure', () {
      if (mlDsaFfi) {
        expect(AtPqc.mlDsa65, isA<MlDsa65FfiAlgo>());
      } else {
        expect(AtPqc.mlDsa65, isA<MlDsa65PureDartAlgo>());
      }
    });

    test('AtPqc.aesGcm256 is FFI when supported, else pure', () {
      if (aesGcmFfi) {
        expect(AtPqc.aesGcm256, isA<AesGcm256FfiAlgo>());
      } else {
        expect(AtPqc.aesGcm256, isA<AesGcm256EncryptionAlgo>());
      }
    });

    test('aesGcm256 encrypt/decrypt round-trip', () async {
      final Uint8List key = AtPqc.aesGcm256.generateKey();
      final InitialisationVector iv = InitialisationVector.random(12);
      final Uint8List plain = Uint8List.fromList(utf8.encode('hello pqc aead'));

      final Uint8List encrypted =
          await AtPqc.aesGcm256.encrypt(plain, key, iv: iv);
      final Uint8List decrypted =
          await AtPqc.aesGcm256.decrypt(encrypted, key, iv: iv);
      expect(decrypted, plain);
    });

    test('xWing encapsulate/decapsulate round-trip', () async {
      final kp = await AtPqc.xWing.generateKeyPair();

      final enc = await AtPqc.xWing.encapsulate(kp.publicKey);
      expect(enc.ciphertext.length, 1120);
      expect(enc.sharedSecret.length, 32);

      final ss = await AtPqc.xWing.decapsulate(kp.secretKey, enc.ciphertext);
      expect(ss, enc.sharedSecret);
    });

    test('mlDsa65 signBytes/verifyBytes round-trip', () async {
      final kp = await AtPqc.mlDsa65.generateKeyPair();

      final Uint8List msg = Uint8List.fromList('hello pqc'.codeUnits);
      final Uint8List sig =
          await AtPqc.mlDsa65.signBytes(msg, secretKey: kp.secretKey);
      final bool ok = await AtPqc.mlDsa65
          .verifyBytes(msg, signature: sig, publicKey: kp.publicKey);
      expect(ok, isTrue);
    });

    test('AtPqc.xWing.generateKeyPair() round-trips directly', () async {
      final kp = await AtPqc.xWing.generateKeyPair();
      expect(kp.publicKey.length, 1216);
      expect(kp.secretKey.length, 32);

      final enc = await AtPqc.xWing.encapsulate(kp.publicKey);
      final ss = await AtPqc.xWing.decapsulate(kp.secretKey, enc.ciphertext);
      expect(ss, enc.sharedSecret);
    });

    test('AtPqc.mlDsa65.generateKeyPair() round-trips directly', () async {
      final kp = await AtPqc.mlDsa65.generateKeyPair();
      expect(kp.publicKey.length, 1952);
      expect(kp.secretKey.length, 4032);

      final Uint8List msg =
          Uint8List.fromList('direct facade keygen'.codeUnits);
      final Uint8List sig =
          await AtPqc.mlDsa65.signBytes(msg, secretKey: kp.secretKey);
      expect(
          await AtPqc.mlDsa65
              .verifyBytes(msg, signature: sig, publicKey: kp.publicKey),
          isTrue);
    });

    test(
        'pure-Dart X-Wing keys are interoperable with AtPqc.xWing regardless '
        'of which backend AtPqc selects', () async {
      // Keys generated by the pure-Dart backend must round-trip through
      // whatever backend AtPqc resolves to (FFI or pure). This pins the two
      // backends stay wire-compatible.
      final kp = await XWingPureDartAlgo.instance.generateKeyPair();
      final enc = await AtPqc.xWing.encapsulate(kp.publicKey);
      final ss = await AtPqc.xWing.decapsulate(kp.secretKey, enc.ciphertext);
      expect(ss, enc.sharedSecret);
    });

    test(
        'pure-Dart ML-DSA-65 keys are interoperable with AtPqc.mlDsa65 '
        'regardless of which backend AtPqc selects', () async {
      final kp = await MlDsa65PureDartAlgo().generateKeyPair();
      final Uint8List msg =
          Uint8List.fromList('cross-backend key reuse'.codeUnits);
      final Uint8List sig =
          await AtPqc.mlDsa65.signBytes(msg, secretKey: kp.secretKey);
      expect(
          await AtPqc.mlDsa65
              .verifyBytes(msg, signature: sig, publicKey: kp.publicKey),
          isTrue);
    });
  });

  // These tests require libcrypto (OpenSSL >= 3.5) at runtime.
  // They are tagged 'ffi' and intentionally FAIL (not skip) when the library
  // is missing or too old — CI must provide OpenSSL before running --tags ffi.
  group('AtPqc — FFI cross-backend interop', () {
    test('X-Wing: FFI encapsulate, pure-Dart decapsulate', () async {
      if (lib == null) fail('libcrypto not available on this host');
      if (!xWingFfi) {
        fail('libcrypto does not support ML-KEM-768 (requires OpenSSL >= 3.5)');
      }

      final kp = await XWingPureDartAlgo.instance.generateKeyPair();
      final ffiAlgo = XWingFfiAlgo.fromLib(lib);
      final enc = await ffiAlgo.encapsulate(kp.publicKey);
      final ss = await XWingPureDartAlgo.instance
          .decapsulate(kp.secretKey, enc.ciphertext);
      expect(ss, enc.sharedSecret);
    }, tags: ['ffi']);

    test('X-Wing: pure-Dart encapsulate, FFI decapsulate', () async {
      if (lib == null) fail('libcrypto not available on this host');
      if (!xWingFfi) {
        fail('libcrypto does not support ML-KEM-768 (requires OpenSSL >= 3.5)');
      }

      final kp = await XWingPureDartAlgo.instance.generateKeyPair();
      final enc = await XWingPureDartAlgo.instance.encapsulate(kp.publicKey);
      final ffiAlgo = XWingFfiAlgo.fromLib(lib);
      final ss = await ffiAlgo.decapsulate(kp.secretKey, enc.ciphertext);
      expect(ss, enc.sharedSecret);
    }, tags: ['ffi']);

    test('ML-DSA-65: FFI sign, pure-Dart verify', () async {
      if (lib == null) fail('libcrypto not available on this host');
      if (!mlDsaFfi) {
        fail('libcrypto does not support ML-DSA-65 (requires OpenSSL >= 3.5)');
      }

      final kp = await MlDsa65PureDartAlgo().generateKeyPair();
      final Uint8List msg = Uint8List.fromList('cross-backend sign'.codeUnits);
      final ffiAlgo = MlDsa65FfiAlgo.fromLib(lib);
      final Uint8List sig =
          await ffiAlgo.signBytes(msg, secretKey: kp.secretKey);
      final bool ok = await MlDsa65PureDartAlgo()
          .verifyBytes(msg, signature: sig, publicKey: kp.publicKey);
      expect(ok, isTrue);
    }, tags: ['ffi']);

    test('ML-DSA-65: pure-Dart sign, FFI verify', () async {
      if (lib == null) fail('libcrypto not available on this host');
      if (!mlDsaFfi) {
        fail('libcrypto does not support ML-DSA-65 (requires OpenSSL >= 3.5)');
      }

      final kp = await MlDsa65PureDartAlgo().generateKeyPair();
      final Uint8List msg =
          Uint8List.fromList('cross-backend verify'.codeUnits);
      final Uint8List sig =
          await MlDsa65PureDartAlgo().signBytes(msg, secretKey: kp.secretKey);
      final ffiAlgo = MlDsa65FfiAlgo.fromLib(lib);
      final bool ok = await ffiAlgo.verifyBytes(msg,
          signature: sig, publicKey: kp.publicKey);
      expect(ok, isTrue);
    }, tags: ['ffi']);
  });
}
