/// Executes the gates a [GateConfig] describes.
///
/// Decides nothing (that is `verdict.dart`) and prints nothing (that is
/// `bin/wasm_shakedown.dart`).
library;

import 'dart:io';

import 'config.dart';
import 'verdict.dart';
import 'wasm_shakedown.dart';

/// Where generated probes and their output live: gitignored, and under the
/// workspace root so walking up from a probe reaches the package config.
const probeDirName = '.dart_tool/wasm_shakedown';

/// One ratchet's outcome.
class RatchetOutcome {
  final RatchetSpec spec;
  final RatchetVerdict verdict;
  RatchetOutcome(this.spec, this.verdict);
  bool get holds => verdict.holds;
}

/// One control's outcome.
class ControlOutcome {
  final ControlSpec spec;
  final ControlVerdict verdict;
  ControlOutcome(this.spec, this.verdict);
  bool get holds => verdict.holds;
}

/// The compile probe's outcome.
class ProbeOutcome {
  final List<String> barrels;

  /// Where the generated entry point was written. Kept on failure so the
  /// command can be re-run by hand; deleted on success.
  final String source;

  final bool holds;
  final String output;

  ProbeOutcome({
    required this.barrels,
    required this.source,
    required this.holds,
    required this.output,
  });
}

/// Everything one package's gate produced.
class GateResult {
  final String package;
  final List<RatchetOutcome> ratchets;
  final List<ControlOutcome> controls;
  final ProbeOutcome probe;

  GateResult(this.package, this.ratchets, this.controls, this.probe);

  bool get holds =>
      ratchets.every((r) => r.holds) &&
      controls.every((c) => c.holds) &&
      probe.holds;

  List<String> get failures => [
        for (final r in ratchets) ...r.verdict.failures,
        for (final c in controls) ...c.verdict.failures,
      ];
}

/// Runs gates against a checkout.
class GateRunner {
  /// The pub workspace root. Probes are generated beneath it because
  /// `dart compile wasm` has no `--packages` flag and walks up from the entry
  /// file to find `package_config.json` — one under [Directory.systemTemp] has
  /// none above it and resolves nothing.
  final Directory root;

  GateRunner({Directory? root, Directory? from})
      : root = root ?? workspaceRoot(from: from);

  /// Runs one package's ratchets, controls and compile probe.
  Future<GateResult> run(PackageGate gate) async => GateResult(
        gate.package,
        [
          for (final spec in gate.ratchets)
            RatchetOutcome(
                spec,
                RatchetVerdict(shakedown(spec.barrel, from: root),
                    barrel: spec.barrel,
                    package: gate.package,
                    allowedOffenders: spec.allowedOffenders,
                    maxBlockedPackages: spec.maxBlockedPackages,
                    minFilesWalked: spec.minFilesWalked)),
        ],
        [
          for (final spec in gate.controls)
            ControlOutcome(
                spec,
                ControlVerdict(
                    shakedown(spec.barrel,
                        environment: spec.environment, from: root),
                    barrel: spec.barrel,
                    package: gate.package,
                    because: spec.because,
                    reachesFile: spec.reachesFile,
                    reachesLibrary: spec.reachesLibrary)),
        ],
        await _probe(gate),
      );

  Future<ProbeOutcome> _probe(PackageGate gate) async {
    final dir = Directory('${root.path}/$probeDirName/${gate.package}')
      ..createSync(recursive: true);
    final source = File('${dir.path}/probe.dart')
      ..writeAsStringSync(probeSource(gate));

    final result = await Process.run(Platform.resolvedExecutable,
        ['compile', 'wasm', source.path, '-o', '${dir.path}/out.wasm'],
        workingDirectory: root.path);

    final holds = result.exitCode == 0;
    // The whole directory: a wasm compile emits .wasm, .mjs, .support.js and
    // .wasm.map today and may emit more. Kept on failure so the generated entry
    // point that would not compile is still there to re-run.
    if (holds) dir.deleteSync(recursive: true);

    return ProbeOutcome(
      barrels: gate.probe,
      source: source.path,
      holds: holds,
      output: '${result.stdout}${result.stderr}'.trim(),
    );
  }

  /// The entry point compiled for [gate]. A probe importing nothing compiles
  /// clean forever, so these imports are the whole content of the gate.
  static String probeSource(PackageGate gate) => '''
// GENERATED by `dart run wasm_shakedown` from .github/wasm_gates.yaml. Edit the
// config, not this file. Compiled, never run.
// ignore_for_file: unused_import
${gate.probe.map((b) => "import '$b';").join('\n')}

void main() {}
''';
}
