name: at_lookup
description: A Dart library that contains the core commands that can be used with a secondary server (scan, update, lookup, llookup, plookup, etc.)
version: 3.6.0
repository: https://github.com/atsign-foundation/at_client_sdk/tree/trunk/packages/at_lookup
homepage: https://atsign.com
documentation: https://docs.atsign.com/

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  at_utils: ^3.0.19
  at_commons: ^5.13.0
  mutex: ^3.0.0
  meta: ^1.16.0
  at_chops: ^3.3.0

dev_dependencies:
  mocktail: ^1.0.4
  lints: ^6.0.0
  test: ^1.25.0
