const String KEYCHAIN_ATSIGN = '@atsign';
const String KEYCHAIN_HIVE_SECRET = '_hive_secret';
const String KEYCHAIN_SECRET = '_secret';
const String KEYCHAIN_PKAM_PRIVATE_KEY = '_pkam_private_key';
const String KEYCHAIN_PKAM_PUBLIC_KEY = '_pkam_public_key';
const String KEYCHAIN_ENCRYPTION_PRIVATE_KEY = '_encryption_private_key';
const String KEYCHAIN_ENCRYPTION_PUBLIC_KEY = '_encryption_public_key';
const String KEYCHAIN_SELF_ENCRYPTION_KEY = '_aesKey';

const List<String> KEYCHAIN_KEYS_LIST = [
  KEYCHAIN_ATSIGN,
  KEYCHAIN_HIVE_SECRET,
  KEYCHAIN_SECRET,
  KEYCHAIN_PKAM_PRIVATE_KEY,
  KEYCHAIN_PKAM_PUBLIC_KEY,
  KEYCHAIN_ENCRYPTION_PRIVATE_KEY,
  KEYCHAIN_ENCRYPTION_PUBLIC_KEY,
  KEYCHAIN_SELF_ENCRYPTION_KEY
];
