name: at_policy_example
description: Simple at_policy usage examples
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  at_policy: ^1.1.0
  at_cli_commons: ^1.2.1
  at_client: ^3.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
