name: at_commons
description: A library of Dart and Flutter utility classes that are used across other components of the atPlatform.
version: 5.15.0
repository: https://github.com/atsign-foundation/at_client_sdk/tree/trunk/packages/at_commons
homepage: https://atsign.com
documentation: https://docs.atsign.com/

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  json_annotation: ^4.9.0
  meta: ^1.16.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  lints: ^6.0.0
  test: ^1.25.0
  test_process: ^2.1.0
