// Regenerates test/vectors/jws_envelope.json — the committed JWS
// signed-envelope vectors an off-the-shelf verifier checks
// (tool/verify_jws_vectors.mjs). Run from packages/at_client:
//
//   dart tool/generate_jws_vectors.dart
//
// The keys in the vector file are TEST FIXTURES generated by this script,
// never used anywhere else; the privates are committed so the RS256 arm can
// be re-signed and compared byte-for-byte (PKCS#1 v1.5 is deterministic —
// ML-DSA is hedged, so that arm is verified rather than re-signed).
import 'dart:convert';
import 'dart:io';

import 'package:at_chops/at_chops.dart';
import 'package:at_client/src/signing/envelope_signature.dart';

Future<void> main() async {
  const payload = {'doc': 'JWS signed-envelope vector', 'n': 1};

  final rsaPair = AtChopsUtil.generateAtPkamKeyPair();
  final rsaEnvelope = signEnvelope(payload,
      keys: [
        ApkamSigningKeys(
            algorithm: SigningAlgoType.rsa2048,
            publicKey: rsaPair.atPublicKey.publicKey,
            privateKey: rsaPair.atPrivateKey.privateKey)
      ],
      type: EnvelopeType.app,
      enrollmentId: 'vector-1');

  final mlDsaPair = await MlDsa65PureDartAlgo().generateKeyPair();
  final mlDsaEnvelope = signEnvelope(payload,
      keys: [
        ApkamSigningKeys(
            algorithm: SigningAlgoType.mldsa65,
            publicKey: base64Encode(mlDsaPair.publicKey),
            privateKey: base64Encode(mlDsaPair.secretKey))
      ],
      type: EnvelopeType.app,
      enrollmentId: 'vector-1');

  final out = const JsonEncoder.withIndent('  ').convert({
    'comment': 'JWS signed-envelope vectors, RFC 7515 general JSON '
        'serialization. Each protected header carries a `typ` naming what the '
        'envelope was signed for, and a verifier is handed the type it '
        'expects rather than reading this one. Test fixtures only — the keys '
        'exist for this file alone. See docs/projects/pq/decisions.md 60.4.',
    'payload': payload,
    'rs256': {
      'envelope': rsaEnvelope,
      // The _apsk form a verifier fetches: the bare base64-DER RSA string.
      'apskPublicKey': rsaPair.atPublicKey.publicKey,
      'privateKey': rsaPair.atPrivateKey.privateKey,
    },
    'mlDsa65': {
      'envelope': mlDsaEnvelope,
      // The raw ML-DSA-65 public key, base64 — what an _apsk entry's `pub`
      // carries.
      'publicKey': base64Encode(mlDsaPair.publicKey),
      'secretKey': base64Encode(mlDsaPair.secretKey),
    },
  });

  final file = File('test/vectors/jws_envelope.json');
  file.createSync(recursive: true);
  file.writeAsStringSync('$out\n');
  stdout.writeln('wrote ${file.path}');
}
