// Regenerates test/vectors/jws_envelope.json — the committed JWS
// signed-envelope vectors an off-the-shelf verifier checks
// (tool/verify_jws_vectors.mjs). Run from packages/at_client:
//
//   dart tool/generate_jws_vectors.dart
//
// The keys in the vector file are TEST FIXTURES generated by this script,
// never used anywhere else; the privates are committed so the RS256 arm can
// be re-signed and compared byte-for-byte (PKCS#1 v1.5 is deterministic —
// ML-DSA is hedged, so that arm is verified rather than re-signed).
import 'dart:convert';
import 'dart:io';

import 'package:at_chops/at_chops.dart';
import 'package:at_client/src/signing/envelope_signature.dart';

Future<void> main() async {
  const payload = {'doc': 'JWS signed-envelope vector', 'n': 1};

  // REUSE the committed key material when there is any. A format change has to
  // re-sign these vectors, and minting fresh keys as well would rewrite every
  // byte of the file - which destroys the one thing it is for during a review:
  // the diff of a golden file is how a reviewer sees what moved on the wire
  // without opening a single writer. With the keys held still, that diff is
  // exactly the header change and the signatures over it.
  final existing = File('test/vectors/jws_envelope.json');
  final Map<String, dynamic>? prior = existing.existsSync()
      ? jsonDecode(existing.readAsStringSync()) as Map<String, dynamic>
      : null;
  final priorRs = prior?['rs256'] as Map<String, dynamic>?;
  final priorMl = prior?['mlDsa65'] as Map<String, dynamic>?;

  final rsaPair = AtChopsUtil.generateAtPkamKeyPair();
  final rsaPublic =
      priorRs?['apskPublicKey'] as String? ?? rsaPair.atPublicKey.publicKey;
  final rsaPrivate =
      priorRs?['privateKey'] as String? ?? rsaPair.atPrivateKey.privateKey;
  final rsaEnvelope = signEnvelope(payload,
      keys: [
        ApkamSigningKeys(
            algorithm: SigningAlgoType.rsa2048,
            publicKey: rsaPublic,
            privateKey: rsaPrivate)
      ],
      type: EnvelopeType.app,
      enrollmentId: 'vector-1');

  final mlDsaPair = await MlDsa65PureDartAlgo().generateKeyPair();
  final mlDsaPublic =
      priorMl?['publicKey'] as String? ?? base64Encode(mlDsaPair.publicKey);
  final mlDsaSecret =
      priorMl?['secretKey'] as String? ?? base64Encode(mlDsaPair.secretKey);
  final mlDsaEnvelope = signEnvelope(payload,
      keys: [
        ApkamSigningKeys(
            algorithm: SigningAlgoType.mldsa65,
            publicKey: mlDsaPublic,
            privateKey: mlDsaSecret)
      ],
      type: EnvelopeType.app,
      enrollmentId: 'vector-1');

  final out = const JsonEncoder.withIndent('  ').convert({
    'comment': 'JWS signed-envelope vectors, RFC 7515 general JSON '
        'serialization. Each protected header carries a `typ` naming what the '
        'envelope was signed for, and a verifier is handed the type it '
        'expects rather than reading this one. Test fixtures only — the keys '
        'exist for this file alone. See docs/projects/pq/decisions.md 60.4.',
    'payload': payload,
    'rs256': {
      'envelope': rsaEnvelope,
      // The _apsk form a verifier fetches: the bare base64-DER RSA string.
      'apskPublicKey': rsaPublic,
      'privateKey': rsaPrivate,
    },
    'mlDsa65': {
      'envelope': mlDsaEnvelope,
      // The raw ML-DSA-65 public key, base64 — what an _apsk entry's `pub`
      // carries.
      'publicKey': mlDsaPublic,
      'secretKey': mlDsaSecret,
    },
  });

  final file = File('test/vectors/jws_envelope.json');
  file.createSync(recursive: true);
  file.writeAsStringSync('$out\n');
  stdout.writeln('wrote ${file.path}');
}
