name: at_client_mobile
description: A Flutter extension to the at_client library which adds support for mobile, desktop and IoT devices.
version: 3.2.8
repository: https://github.com/atsign-foundation/at_client_sdk/packages
homepage: https://docs.atsign.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.2
  flutter:
    sdk: flutter
  package_info_plus: ^1.4.2
  flutter_keychain: ^2.2.1
  biometric_storage: ^4.1.3
  hive: ^2.0.4
  crypton: ^2.0.3
  at_client: ^3.0.50
  at_lookup: ^3.0.35
  at_commons: ^3.0.34
  at_utils: ^3.0.11
  at_chops: ^1.0.0

#dependency_overrides:
#  at_client:
#    git:
#      url: https://github.com/atsign-foundation/at_client_sdk.git
#      path: packages/at_client
#      ref: uptake_atchops
#  at_chops:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: packages/at_chops
#      ref: at_chops
#  at_commons:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_commons
#      ref: trunk
#   at_client:
#     path: ../at_client
#    git:
#      url: https://github.com/atsign-foundation/at_client_sdk.git
#      path: at_lookup
#      ref: trunk
#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: trunk
#  at_utils:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_utils
#      ref: trunk

dev_dependencies:
  lints: ^2.0.0
  test: ^1.6.0
