name: at_client_mobile
description: A Flutter extension to the at_client library which adds support for mobile, desktop and IoT devices.
version: 3.2.10
repository: https://github.com/atsign-foundation/at_client_sdk/packages
homepage: https://docs.atsign.com/

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  path: ^1.8.2
  flutter:
    sdk: flutter
  package_info_plus: 3.1.0
  flutter_keychain: ^2.2.1
  biometric_storage: ^4.1.3
  hive: ^2.0.4
  crypton: ^2.0.3
  at_commons: ^3.0.47
  at_utils: ^3.0.13
  at_chops: ^1.0.3
  at_lookup: ^3.0.37
  at_client: ^3.0.60

dev_dependencies:
  lints: ^2.0.0
  test: ^1.6.0
  mocktail: ^0.3.0
