name: at_client_mobile
description: A Flutter extension to the at_client library which adds support for mobile, desktop and IoT devices.
version: 3.2.12
repository: https://github.com/atsign-foundation/at_client_sdk/packages
homepage: https://docs.atsign.com/

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  path: ^1.8.2
  flutter:
    sdk: flutter
  package_info_plus: ^4.0.2
  flutter_keychain: ^2.2.1
  biometric_storage: ^5.0.0
  hive: ^2.0.4
  crypton: '>=2.1.0 <=2.2.0'
  at_commons: ^3.0.53
  at_utils: ^3.0.15
  at_chops: ^1.0.3
  at_lookup: ^3.0.38
  at_client: ^3.0.64

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_commons
      ref: trunk
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: packages/at_persistence_secondary_server
      ref: uptake_commons_4.0.0
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: uptake_commons_changes_into_lookup
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: uptake_commons_4.0.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.6.0
  mocktail: ^0.3.0
