name: at_client_example
description: An example application to demostrate the at_client package usage.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <4.0.0'

dependency_overrides:
  at_client:
    path: ../../at_client
  at_commons: ^4.0.0
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: packages/at_persistence_secondary_server
      ref: uptake_commons_4.0.0
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: uptake_commons_changes_into_lookup
  at_chops:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_chops
      ref: at_chops_dep_upgrade

dependencies:
  at_client: ^3.0.37

dev_dependencies:
  lints: ^1.0.0
