name: at_client_example
description: An example application to demostrate the at_client package usage.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <4.0.0'

dependency_overrides:
  at_client:
    path: ../../at_client

dependencies:
  at_client: ^3.0.37

dev_dependencies:
  lints: ^1.0.0
