name: at_client_examples
description: Examples of some of the most common usages of the at_client package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.0"

dependencies:
  at_client: ^3.11.0
  at_cli_commons: ^3.1.0
  at_commons: ^5.8.0
  at_onboarding_cli: ^2.0.0
  at_utils: ^3.4.0
  args: ^2.5.0
  nocterm: ^0.6.0

dependency_overrides:
  at_client:
    path: ../../at_client
  at_cli_commons:
    path: ../../at_cli_commons
  at_chops:
    path: ../../at_chops
  at_commons:
    path: ../../at_commons
  at_lookup:
    path: ../../at_lookup
  at_auth:
    path: ../../at_auth
  at_onboarding_cli:
    path: ../../at_onboarding_cli

dev_dependencies:
  lints: ^6.1.0
