name: at_client_examples
description: Examples of some of the most common usages of the at_client package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0"

dependencies:
  at_client: ^3.11.0
  at_cli_commons: ^3.0.1
  at_commons: ^5.8.0
  at_utils: ^3.4.0

dependency_overrides:
  at_client:
    path: ../../at_client
  at_cli_commons:
    path: ../../at_cli_commons
  at_commons:
    path: ../../at_commons

dev_dependencies:
  lints: ^6.1.0
