name: at_client_example
description: An example application to demonstrate the at_client package usage.
version: 1.0.0

environment:
  sdk: ">=2.15.0 <4.0.0"

dependency_overrides:
  at_client:
    path: ../../at_client
  at_commons:
    path: ../../at_commons
  at_chops:
    path: ../../at_chops
  at_auth:
    path: ../../at_auth
  at_lookup:
    path: ../../at_lookup

dependencies:
  at_client: ^3.7.0

dev_dependencies:
  lints: ^1.0.0
