import 'package:at_commons/at_commons.dart';

import 'namespace_permission.dart';

/// The BaseEnrollmentRequest class encapsulates shared fields between the InitialEnrollmentRequest and EnrollmentRequest.
///
/// The [FirstEnrollmentRequest] is used when the app is onboarded for the first time. The request is sent to the server
/// via the CRAM authenticated connection and is auto approved.
///
/// The [EnrollmentRequest] is used by the other apps to authenticate. This request is sent to the server and subsequently
/// notified to apps with access to the "__manage" namespace. Upon approval, the requesting app is authenticated and granted
/// authorization to access the specified namespaces in the request. Conversely, if the request is disapproved, the requesting
/// app is denied login access.
abstract class EnrollmentRequest {
  Atsign atsign;
  String appName;
  String deviceName;
  final EnrollOperationEnum enrollOperation = EnrollOperationEnum.request;
  AtRootDomain rootDomain;

  EnrollmentRequest(
      {required this.atsign,
      required this.appName,
      required this.deviceName,
      this.rootDomain = AtRootDomain.atsignDomain});
}

/// The [EnrollmentRequest] is used by the apps to submit enrollment request for APKAM keys which provides .atKeys specific to
/// an application with restricted access to the namespaces. The application can access only the namespaces which are specified
/// in the enrollment request. If the namespace has Read-Write access then the application is allowed to create/update the data,
/// otherwise, if the namespace has only Read access then the application is allowed to read the data, but cannot create/update
/// the data.
///
/// This request is sent to the server and subsequently notified to apps with access to the "__manage" namespace. Upon approval, the requesting app is authenticated and granted
/// authorization to access the specified namespaces in the request. Conversely, if the request is disapproved, the requesting
/// app is denied login access.
class AtEnrollmentRequest extends EnrollmentRequest {
  List<NamespacePermission> namespaces;
  String otp;
  Duration? apkamKeysExpiryDuration;

  /// The APKAM keypair for a subsequent enrollment is minted while the request
  /// is submitted, so this request carries no public key of its own — only
  /// [FirstEnrollmentRequest], whose keypair is minted during activation, does.
  AtEnrollmentRequest({
    required super.atsign,
    required super.appName,
    required super.deviceName,
    required this.otp,
    required this.namespaces,
    super.rootDomain,
    this.apkamKeysExpiryDuration,
  });
}

/// The FirstEnrollmentRequest represents an enrollment request when onboarding (activating) an atSign.
///
/// Upon submitting the [FirstEnrollmentRequest], an APKAM key pair and an encryption key pair are generated, and an enrollment
/// request is sent to the server. The server assigns the "__manage" namespace, which has access to all namespaces and serves as
/// the administrator app responsible for approving subsequent enrollment requests.
///
/// ```dart
/// Example on submitting FirstEnrollmentRequest
///   FirstEnrollmentRequest firstEnrollmentRequest = FirstEnrollmentRequest(
///               appName: 'wavi',
///               deviceName: 'iphone',
///               apkamPublicKey: 'dummy-apkam-public key', // Generated by the system
///               encryptedDefaultEncryptionPrivateKey: 'dummy-encrypted-private-key', // Generated by the system and encrypted by the APKAM symmetric key
///               encryptedDefaultSelfEncryptionKey: 'dummy-self-encryption-key'); // Generated by the system and encrypted by the APKAM symmetric key);
///```
/// Two pair of RSA key pairs one for authentication which is called APKAM keys and other for shared data encryption
/// which is called encryption key pair. Two AES keys pairs self data encryption and APKAM encryption key.
///
/// The APKAM public key is stored in the secondary server. The default encryption private key and self encryption keys are
/// encrypted with the APKAM symmetric key and stored into the server.

class FirstEnrollmentRequest extends EnrollmentRequest {
  /// The app and device names the atServer records for the auto-approved
  /// enrollment an activation creates.
  static const String defaultAppName = 'firstApp';
  static const String defaultDeviceName = 'firstDevice';

  /// The APKAM public key minted during activation, base64-encoded.
  String apkamPublicKey;

  FirstEnrollmentRequest({
    required super.atsign,
    required this.apkamPublicKey,
    super.appName = defaultAppName,
    super.deviceName = defaultDeviceName,
    super.rootDomain,
  });
}
