/// Local-only setup for running the end-to-end suite against a local virtualenv
/// (`atsigncompany/virtualenv:vip`). Run by `runLocal.sh` before `dart test`.
///
/// It (a) mints `atKeys/<atSign>_key.atKeys` for the PKAM demo atSigns from
/// `at_demo_data` static keys, and (b) writes `config/config.yaml` pointing at
/// the virtualenv root (honouring `VIRTUALENV_BASE_PORT` for base-port runs).
/// Both outputs are gitignored — this never runs in CI.
library;

import 'dart:io';

import 'package:at_auth/at_auth.dart';
import 'package:at_commons/at_commons.dart';
import 'package:at_demo_data/at_demo_data.dart';

/// The local virtualenv root hostname (mapped to 127.0.0.1 in /etc/hosts).
const String rootUrl = 'vip.ve.atsign.zone';

/// PKAM demo atSigns pre-onboarded in the virtualenv image (the 🛠 set in
/// at_demo_data). Used as first/second/third/fourth in the generated config.
const List<String> atSigns = ['@alice🛠', '@bob🛠', '@colin🛠', '@eve🛠'];

Future<void> main() async {
  // Root port = VIRTUALENV_BASE_PORT for a base-port virtualenv, else the
  // standard root port 64.
  final basePort =
      int.tryParse(Platform.environment['VIRTUALENV_BASE_PORT'] ?? '') ?? 64;

  // FileAtKeysIo.write refuses to overwrite, so start from a clean atKeys dir.
  final atKeysDir = Directory('atKeys');
  if (atKeysDir.existsSync()) atKeysDir.deleteSync(recursive: true);
  atKeysDir.createSync(recursive: true);

  for (final atSign in atSigns) {
    final atKeys = AtKeys()
      ..apkamPublicKey = AtBytes.fromString(pkamPublicKeyMap[atSign]!)
      ..apkamPrivateKey = AtBytes.fromString(pkamPrivateKeyMap[atSign]!)
      ..defaultEncryptionPublicKey =
          AtBytes.fromString(encryptionPublicKeyMap[atSign]!)
      ..defaultEncryptionPrivateKey =
          AtBytes.fromString(encryptionPrivateKeyMap[atSign]!)
      ..defaultSelfEncryptionKey = AtBytes.fromString(aesKeyMap[atSign]!)
      ..apkamSymmetricKey = AtBytes.fromString(apkamSymmetricKeyMap[atSign]!);

    final path = 'atKeys/${atSign}_key.atKeys';
    await FileAtKeysIo(filePath: (_) => path).write(atSign, atKeys);
    stdout.writeln('  wrote $path');
  }

  final atsignList = atSigns.map((a) => "'$a'").join(', ');
  final config = '''
# Generated by test/local_setup.dart for a local virtualenv run. Do NOT commit
# (gitignored). Regenerated on every runLocal.sh invocation.
root_server:
  url: '$rootUrl'
  port: $basePort

atSign:
  firstAtSign: '${atSigns[0]}'
  secondAtSign: '${atSigns[1]}'
  thirdAtSign: '${atSigns[2]}'
  fourthAtSign: '${atSigns[3]}'

enrollment:
  atsignList: [ $atsignList ]

authType: 'apkam'
filePath: 'atKeys'
''';
  File('config/config.yaml').writeAsStringSync(config);
  stdout.writeln('  wrote config/config.yaml (root $rootUrl:$basePort)');
}
