name: at_telemetry
description: telemetry package that defines models, behaviors
              and contracts for applications and atServers
version: 0.1.0
repository: https://github.com/atsign-foundation/at_client_sdk

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  at_utils: ^3.0.19
  crypto: ^3.0.5
  cryptography: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
