name: at_client_flutter
description: A Flutter extension to the at_client library which adds support for mobile, desktop and IoT devices.
version: 0.1.0
repository: https://github.com/atsign-foundation/at_client_sdk/tree/trunk/packages/at_client_mobile
homepage: https://atsign.com
documentation: https://docs.atsign.com/

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.0
  flutter_keychain: ^2.2.1
  biometric_storage: ^5.0.0
  hive: ^2.2.3
  crypton: ^2.2.1
  at_commons: ^5.5.0
  at_utils: ^3.0.19
  at_chops: ^3.0.0
  at_lookup: ^3.0.51
  at_client: ^3.7.0
  at_auth: ^2.1.0
  encrypt: ^5.0.3
  at_persistence_secondary_server: ^4.2.0
  flutter_riverpod: ^3.0.0

dev_dependencies:
  path: ^1.9.0
  lints: ^6.0.0
  test: ^1.25.0
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
