name: static_analysis
# Runs the workflow on the below events:
# 1. on pull request raised to trunk branch.
# 2. on push event to trunk branch.
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - at_backupkey_flutter
          - at_chat_flutter
          - at_common_flutter
          - at_contacts_flutter
          - at_contacts_group_flutter
          - at_events_flutter
          - at_follows_flutter
          - at_invitation_flutter
          - at_location_flutter
          - at_login_flutter
          - at_notify_flutter
          - at_onboarding_flutter
          - at_sync_ui_flutter
          - at_theme_flutter
        flutter-channel:
          - stable
          - beta

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          channel: "${{ matrix.flutter-channel}}"
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "stable"
          cache-dependency-path: tools/osv-scanner/go.sum

      - name: Install dependencies and analyze in ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: |
          touch example/.env
          flutter pub get
          if [ "${{ matrix.flutter-channel}}" = "beta" ]; then
            flutter analyze
          else
            flutter analyze --no-fatal-infos
          fi

      # Runs osv-scanner to find any vulnerable Dart dependencies
      # It needs to look at pubspec.lock files, which is why it's
      # placed here, as the `dart pub get` above will create them
      - name: Run osv-scanner
        working-directory: packages/${{ matrix.package }}
        run: |
          go install github.com/google/osv-scanner/cmd/osv-scanner@6316373e47d7e3e4b4fd3630c4bbc10987738de6 # v1.4.3
          osv-scanner --lockfile=./pubspec.lock

