# This workflows runs when
# 1. pull_request raised to trunk branch.
# 2. tag created on at_tools repository
name: osv-scanner

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  scan-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./actions/setup-flutter-and-dart
        with:
          dart-channel: ${{ matrix.dart-channel}}

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "stable"
          cache-dependency-path: tools/osv-scanner/go.sum

      - name: Install workspace dependencies
        run: dart pub get

      - name: Run osv-scanner
        run: |
          go install github.com/google/osv-scanner/cmd/osv-scanner@6316373e47d7e3e4b4fd3630c4bbc10987738de6 # v1.4.3
          osv-scanner --lockfile=./pubspec.lock

      # Temporary, until at_chops is added to the workspace
      - name: Install at_chops dependencies (temp)
        run: dart pub get
        working-directory: packages/at_chops

      - name: Run osv-scanner in at_chops (temp)
        run: |
          go install github.com/google/osv-scanner/cmd/osv-scanner@6316373e47d7e3e4b4fd3630c4bbc10987738de6 # v1.4.3
          osv-scanner --lockfile=./pubspec.lock
        working-directory: packages/at_chops
