# This workflows runs when
# 1. pull_request raised to trunk branch.
# 2. tag created on at_tools repository
name: osv-scanner

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  scan-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./actions/setup-flutter-and-dart
        with:
          dart-channel: ${{ matrix.dart-channel}}

      - name: Install workspace dependencies
        run: dart pub get

      # Temporary, until at_chops is added to the workspace
      - name: Install at_chops dependencies (temp)
        run: dart pub get
        working-directory: packages/at_chops

      - name: Run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
        with:
          scan-args: |-
            --lockfile=./pubspec.lock
